/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 21839e7d884931f4b8e8a1d3415c6cc4)
interface __BaseEnv_Env {
	FRONTEND_ORIGIN: "https://t-b.es";
	AUTH_ORIGIN: "https://auth.t-b.es";
	GITHUB_OWNER: "to3b";
	GITHUB_REPO: "tobesURLshortener";
	GITHUB_REPOSITORY_ID: "1061521737";
	GITHUB_ALLOWED_LOGIN: "to3b";
	GITHUB_BRANCH: "main";
	GITHUB_FILE: "hello.txt";
	GITHUB_API_VERSION: "2026-03-10";
	GITHUB_CLIENT_ID: string;
	GITHUB_CLIENT_SECRET: string;
	SESSION_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/entry");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FRONTEND_ORIGIN" | "AUTH_ORIGIN" | "GITHUB_OWNER" | "GITHUB_REPO" | "GITHUB_REPOSITORY_ID" | "GITHUB_ALLOWED_LOGIN" | "GITHUB_BRANCH" | "GITHUB_FILE" | "GITHUB_API_VERSION" | "GITHUB_CLIENT_ID" | "GITHUB_CLIENT_SECRET" | "SESSION_SECRET">> {}
}
